---
spring:
  profiles: development
  datasource:
    url: jdbc:h2:~/bookshelf;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
 
  # enable H2 web console and set url for web console
  # http://localhost:8080/console
  h2:
    console:
      enabled: true
      path: /h2
      
  liquibase:
    change-log: classpath:/database/master.xml
---
spring:
  profiles: test

  shell:
    interactive:
          enabled: false

  datasource:
    url: jdbc:h2:mem:~/test;
    #url: jdbc:h2:mem:test;MODE=Mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS TEST;SCHEMA=TEST;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: true
      path: /h2

  liquibase:
    change-log: classpath:/database/master.xml